# .readthedocs.yaml configuration file

version: 2

# Define the build configuration environment
build:
  os: ubuntu-20.04
  tools:
    python: '3.10'

# Define dependencies and build steps for your documentation
python:
  version: 3.10
  install:
    - method: pip
      path: .

# Optionally use `uv` if it is indeed a CLI tool for managing
# dependencies or building the docs, though specifics will vary:
  # - method: shell
  #   command: uv install <your-specific-commands>

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Build extension configuration
formats:
  - pdf
  - epub
