version: 2

build:
   os: ubuntu-24.04
   tools:
      python: "3.10"
   jobs:
      create_environment:
         - asdf plugin add uv
         - asdf install uv latest
         - asdf global uv latest
         - uv venv
      install:
         - uv pip install -r pyproject.toml --extra docs
      build:
         html:
            - uv run sphinx-build -T -b html docs/source $READTHEDOCS_OUTPUT/html
